from . import commands
from . import data_collecting
from . import task_1
from . import task_2
from . import task_3
from . import task_4
from . import task_5
from . import task_6
from . import task_7
from . import task_8
from . import task_9
from . import task_10